import Head from 'next/head'
import { Inter } from '@next/font/google'
import HeaderComponent from '../components/headerComponent'
import { useContextState } from '../context/productContext'
import { MdClose } from 'react-icons/md'
import AllAddedProduct from '../components/products/AllAddedProduct'
import HomeComponent from "../components/HomeComponent"

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const { openAddedProduct, setOpenAddedProduct, paymentOption, setPaymentOption} = useContextState()

  const handleCloseAddedProduct = () => {
    setOpenAddedProduct(false)
    setPaymentOption(false)
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <HeaderComponent />
        <div className='relative'>
          <HomeComponent />
          {openAddedProduct &&
            <div className='fixed top-20 w-full z-50'>
              <div className="flex justify-center ">
                <div className='bg-white min-w-[450px] p-4 shadow-2xl relative'>
                  <div className='w-fit p-2 z-[100] absolute right-4 hover:bg-gray-200 rounded-full cursor-pointer' onClick={handleCloseAddedProduct}>
                    <MdClose className='text-2xl' />
                  </div>
                  <AllAddedProduct />
                </div>
              </div>
            </div>
          }
        </div>
      </div>
    </>
  )
}
