import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import HeaderComponent from '../components/headerComponent'
import NftComponent from '../components/nft/NftComponent'
import { useContextState } from '../context/productContext'
import LoadingComponent from '../components/Loading'

const inter = Inter({ subsets: ['latin'] })

export default function NFTCollections() {
    const { isLoading, } = useContextState()

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>
                {isLoading ?
                    <div>
                        <LoadingComponent />
                    </div>
                    :
                    <div>
                        <HeaderComponent />
                        <NftComponent />
                    </div>
                }
            </div>
        </>
    )
}
